### ISSUE TITLE
Fix Spotify OAuth2 callback issue

### ISSUE THREAD

**Issue by authorbeard** [TheLucasMoore/rails-angular-final-project#1]
Hey Lucas, fellow Flatiron School alum here. Ran into the same Spotify OAuth problem you had. In case you're still chewing on this, though I'd suggest the following. I created a file in config/initializers called spotify_oauth.rb. Here's what it contains: 

`OmniAuth::Strategies::OAuth2.module_eval do 

  option :include_query_string, false

```
def build_access_token
  verifier = request.params["code"]
  url = options.include_query_string ? callback_url : (full_host + script_name + callback_path)
  client.auth_code.get_token(verifier, {:redirect_uri => url}.merge(token_params.to_hash(:symbolize_keys => true)), deep_symbolize(options.auth_token_params))
end
```

end`

I just copied and pasted this from this PR listed in one of the omniauth-spotify issues. Didn't require locking the gem version: https://github.com/intridea/omniauth-oauth2/pull/82/files

Anyway, thought it might help. Looking at your code helped me clear up a few things.

**Comment by TheLucasMoore** [comment]
Thanks @authorbeard! I resolved this by just using [Rspotify](https://github.com/guilhermesad/rspotify). I appreciate the knowledge though. =)

**Comment by authorbeard** [comment]
Oh, cool. I was going to ask if just locking the gem had really sorted
everything out. Though I'd share this on the off chance you were still
tinkering.

---

What I've been up to:
Github http://www.github.com/authorbeard
LinkedIn http://www.linkedin.com/in/michaelsnolan
Hamwater http://hamwater.wordpress.com
